Esc:
  0: Deselect
'r':
  2: Reload
'h':
  0: MoveLeft
'j':
  0: MoveDown
'k':
  0: MoveUp
Home:
  0: FirstHistory
Enter:
  0: Select
'q':
  0: Exit
'l':
  0: MoveRight
Right:
  0: MoveRight
End:
  0: ClearHistory
Up:
  0: MoveUp
Backspace:
  0: Back
F5:
  0: Reload
Left:
  0: MoveLeft
  4: Back
Down:
  0: MoveDown
