Enter:
  0: Select
Down:
  0: MoveDown
Right:
  0: MoveRight
'j':
  0: MoveDown
'q':
  0: Exit
End:
  0: ClearHistory
'h':
  0: MoveLeft
'k':
  0: MoveUp
Esc:
  0: Deselect
Up:
  0: MoveUp
Backspace:
  0: Back
Left:
  4: Back
  0: MoveLeft
F5:
  0: Reload
'l':
  0: MoveRight
Home:
  0: FirstHistory
'r':
  2: Reload
