#! /bin/sh

# ===================================
# |        BSPWM Properties         |
# ===================================

pgrep -x sxhkd > /dev/null || sxhkd &

# Workspace Properties
bspc monitor -d I II III IV V

bspc config border_width            1
bspc config window_gap              5
bspc config split_ratio             0.50
bspc config single_monocle          false
bspc config gapless_monocle         true
bspc config borderless_monocle      true
# bspc config focus_follows_pointer   true
# bspc config pointer_follows_focus   true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# Pointer Properties
bspc config click_to_focus          true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Monitor and Desktop Properties
bspc config top_padding             25
bspc config bottom_padding          10
bspc config left_padding            10
bspc config right_padding           10


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Set Wallpaper
feh --bg-scale $HOME/.dotfiles/assets/wallpapers/crescent_moon_gradient.jpeg

# Applications
picom &
easystroke &

dunst &
# bash ~/.config/polybar/launch.sh --shades &
nitrogen --restore &
sxhkd &
spotifyd &
