#!/usr/bin/env bash

# Battery Daemon
# Get battery status and send notification when battery is low\
# Requires: dunst, notify-send, acpi

# While loop that prints hello every minute
while true; do
    # Calculate battery percentage
    battery_level=$(acpi -b | grep -P -o '[0-9]+(?=%)')

    # Check if battery is charging
    charging=$(acpi -b | grep -o 'Charging')

    # Check if battery is full
    full=$(acpi -b | grep -o 'Full')

    # Calculate time remaining
    time_remaining=$(acpi -b | grep -P -o '[0-9]+(?=:[0-9]+:[0-9]+)')

    # If battery is full and charging, send notification
    if [[ $full == "Full" && $charging == "Charging" ]]; then
        notify-send -u low "  Battery is full." "Please unplug the AC adapter."
        exit
    fi

    # If battery is critical and discharging, send notification
    if [[ $battery_level -le 10 && $charging != "Charging" ]]; then
        notify-send -u critical "  Battery is critically low." "Please plug in the AC adapter."
        exit
    fi

    # If battery is low and discharging, send notification
    if [[ $battery_level -le 20 && $charging != "Charging" ]]; then
        notify-send -u normal "  Battery is low." "Please plug in the AC adapter."
        exit
    fi

    # Wait 1 minute
    sleep 60
done