#!/usr/bin/env bash

# A script that manages wallpapers on Hyprland
# Uses swww as a daemon

# Start swww if it hasn't already started
swww query || swww init

# Set directory for wallpapers
# wallDir="$HOME/.dotfiles/assets/wallpapers/catppuccin"
wallDir="$HOME/.dotfiles/assets/wallpapers/discord-snowsgiving"

# Initialize wallpaper variable
wallpaper=""

# Set a fallback wallpaper
fallback="$HOME/.dotfiles/assets/wallpapers/catppuccin/cat-sound.png"

# If there are no parameters, set a fallback wallpaper
if [ -z "$1" ]; then
    wallpaper="$fallback"
fi

# If the first parameter is "random", set a random wallpaper
if [ "$1" = "random" ]; then
    wallpaper="$wallDir/$(ls $wallDir | shuf -n1)"
fi

# If the first parameter is "set", set the second parameter as the wallpaper
# Make sure the second parameter is a valid file and a valid image
if [ "$1" = "set" ]; then
    if [ -f "$2" ] && file "$2" | grep "image data"; then
        wallpaper="$2"
    else
        wallpaper="$fallback"
    fi
fi

# If the wallpaper variable is still empty, set a fallback wallpaper
if [ -z "$wallpaper" ]; then
    wallpaper="$fallback"
fi

# Set the wallpaper
swww img "$wallpaper" \
    --transition-type grow \
    --transition-duration 2.5 \
    --transition-step 255 \
    --transition-bezier 0.32,0.0,0.67,0.0 # easeInCubic
#   --transition-bezier 0.05,0.25,0.1,0.8