#!/usr/bin/env node
const { execSync } = require('child_process');

function dispatch(dispatcher, monitor, workspace) {
    execSync(`hyprctl dispatch ${dispatcher} ${monitorWorkspaces[monitor][workspace]}`);
}

let focused;

focused = JSON.parse(execSync("hyprctl monitors -j | jq -rc '[ .[].focused ]'").toString());
monitorWorkspaces = {
    0: [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
    1: [11, 12, 13, 14, 15, 16, 17, 18, 19],
    2: [21, 22, 23, 24, 25, 26, 27, 28, 29],
    3: [31, 32, 33, 34, 35, 36, 37, 38, 39],
    4: [41, 42, 43, 44, 45, 46, 47, 48, 49],
};

for (let i = 0; i < focused.length; i++) {
    if (focused[i] == true) {
        focused = i;
        break;
    }
}

switch (process.argv[2]) {
    case "workspace":
        dispatch("workspace", focused, process.argv[3] - 1);
        break;
    case "movetoworkspace":
        dispatch("movetoworkspace", focused, process.argv[3] - 1);
        break;
    case "movetoworkspacesilent":
        dispatch("movetoworkspacesilent", focused, process.argv[3] - 1);
        break;
}


// console.log(focused);
// console.log(monitors);
// console.log(process.argv.slice(2));
// console.log(JSON.parse(execSync("hyprctl monitors -j").toString()));