# ~/.config/starship.toml

# Get editor completions based on the config schema.
"$schema" = 'https://starship.rs/config-schema.json'

# -------------------- General Settings --------------------

# Set the default palette.
palette = 'catppuccin_mocha'

# -------------------- Prompt Format --------------------

# The main prompt format.
format = """
[](fg:mauve)\
$os\
$username\
[](bg:lavender fg:mauve)\
$directory\
[](bg:yellow fg:lavender)\
$git_branch\
$git_status\
[ ](fg:yellow)\
$cmd_duration\
$line_break\
$character"""

# The right prompt format (disabled).
# right_format = '''
# [](fg:red)
# [$time](bg:red)
# [](fg:red)$ssh_symbol
# '''

# -------------------- Module Configurations --------------------

# -- Hostname --
[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = "bg:blue fg:mantle bold"
disabled = true

# -- Operating System --
[os]
disabled = false
style = "bg:mauve fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# -- Username --
[username]
show_always = true
style_user = "bg:mauve fg:crust bold"
style_root = "bg:mauve fg:crust bold"
format = '[ $user]($style)'

# -- Directory --
[directory]
truncation_length = 0
format = '[ $home_symbol$path]($style)[$read_only]($read_only_style)'
home_symbol = "~"
style = "bg:lavender fg:base bold"

# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
# "Projects" = "󰏗 "
# "Sandbox" = "󰒋 "

# -- Git Branch --
[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

# -- Git Status --
[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind)](fg:crust bg:yellow)]($style)'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

# -- Time --
[time]
disabled = false
time_format = "%H:%M:%S"
format = ' $time'

# -- Line Break --
[line_break]
disabled = false

# -- Character --
[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

# -- Command Duration --
[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

# -------------------- Color Palettes --------------------

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"