#!/usr/bin/env bash

# This script is used to create a new Hyprland instance.

# === Environment Variables ===
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
# export XDG_CURRENT_DESKTOP=sway
# export XDG_SESSION_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1

# = Cursor Settings ===
# export XCURSOR_PATH=/usr/share/icons:$HOME/.local/share/icons:$HOME/.icons
# export XCURSOR_THEME=BreezeX-Dark
# export XCURSOR_SIZE=24
hyprctl setcursor BreezeX-Dark 24

# === Random Stuff ===
export _JAVA_AWT_WM_NONREPARENTING=1

# === Start Hyprland ===
exec Hyprland