const settings = {
	global: {
		// Class to Title replacements for windows
		'classReplacements': {
			'Desktop': '  Desktop',

			'firefoxdeveloperedition': '󰈹 Firefox Developer Edition',
			'"firefoxdeveloperedition"': '󰈹 Firefox Developer Edition',
			'firefox-developer-edition': '󰈹 Firefox Developer Edition',
			'kitty': '󰆍 Kitty',
			'org.prismlauncher.PrismLauncher': '󰍳 Prism Launcher',
			'blueberry.py': ' Blueberry',
			'org.gnome.Nautilus': ' Nautilus',
			'gnome-terminal-server': '󰆍 GNOME Terminal',
			'gnome-disks': ' GNOME Disks',
			'thunderbird': ' Thunderbird',
			'Google-chrome-unstable': ' Google Chrome [Unstable]',
			'Thorium-browser': ' Thorium Browser',
			'Cromite': ' Cromite Browser',
			'code-oss': '󰨞 Microsoft VS Code [OSS]',
			'Code - Insiders': '󰨞 Microsoft VS Code [Insiders]',
			'code-insiders': '󰨞 Microsoft VS Code [Insiders]',
			'com.github.hluk.copyq': ' CopyQ',
			'discord': '󰙯 Discord',
			'osu!': '󰊗 osu!',
			'launcher': '󰍳 Lunar Client',
			'pavucontrol': '  PulseAudio Volume Control',
			'org.pulseaudio.pavucontrol': '  PulseAudio Volume Control',
			'blueman-manager': ' Blueman Manager',
			'obsidian': '󰎞 Obsidian',
			'qalculate-gtk': '󱖦 Qalculate!',
			'com.obsproject.Studio': ' OBS Studio',
			'neovide': ' Neovide',
			'Bitwarden': '󰟵 Bitwarden',
			'FreeTube': '󰗃 FreeTube',
			'Spotify': ' Spotify',
			'Alacritty': '󰆍 Alacritty',
			'calibre-gui': ' Calibre [Library]',
			'calibre-ebook-viewer': ' Calibre [E-book Viewer]',
			'io.github.seadve.Kooha': ' Kooha',
			'hyprland-share-picker': ' Hyprland Share Picker',
			'gedit': '󰎞 Gedit',
			'mpv': '  MPV',
			'Pulse Browser': '󰈹 Pulse Browser',
			'mercury-default': '󰈹 Mercury Browser',
			'zen': '󰈹 Zen Browser',
			'zen-beta': '󰈹 Zen Browser',
			'zoom': ' Zoom',
			'Twitch': ' Twitch',
			'org-jdownloader-update-launcher-JDLauncher': ' JDownloader',
			'org.gnome.Settings': ' Settings',
			'org.gnome.clocks': ' Clocks',
			'Waydroid': ' Waydroid',
			'chat-gpt': '󰭻 ChatGPT',
			'chatterino': ' Chatterino',
			'flameshot': '󰹑 Flameshot',
			'harmonoid': 'p Harmonoid',
			'vesktop': '󰙯 Vesktop',
			'jetbrains-idea': '󰨞 IntelliJ IDEA',
			'geany': '󰎞 Geany',
			'org.vinegarhq.Sober': '  Sober (Roblox)',
			'sublime_text': '󰎞 Sublime Text',
			'org.gnome.font-viewer': '󰎞 Font Viewer',
			'com.chatterino.chatterino': ' Chatterino',
			'steam': ' Steam',
			'lunarclient': '󰍳 Lunar Client',
			'rustdesk': '󰢹 RustDesk',
			'dev.deedles.Trayscale': '󰖂 Trayscale',
			'syncthing-gtk': '󰘿 Syncthing GTK',
			'org.gnome.gedit': '󰎞 Gedit',
		},
	},
};

export default settings;
