id = 677226551607033903
hosts = ["localhost:6600"]

[format]
title = "Music Player Daemon"
details = "$title"
state = "$album | $album"
timestamp = "elapsed"
large_image = "notes"
small_image = "notes"
large_text = ""
small_text = ""
