#!/usr/bin/env bash

# This script is used to create a new Hyprland instance.

# === Environment Variables ===
# export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XCURSOR_SIZE=24

# === Start Hyprland ===
exec Hyprland